# Generated by Django 2.1.1 on 2018-09-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
